name       : gtk-doc
version    : 1.24
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gtk-doc/1.24/gtk-doc-1.24.tar.xz : b420759ea05c760301bada14e428f1b321f5312f44e10a176d6804822dabb58b
homepage   : http://www.gtk.org/gtk-doc/
license    : GPL-2.0
summary    : GTK API Documentation generator
description: |
    GTK-Doc is a project which was started to generate API documentation from comments added to C code. It is typically used to document the public API of GTK+ and GNOME libraries, but it can also be used to document application code.
builddeps  :
    - pkgconfig(glib-2.0)
    - docbook-xml
patterns   :
    - /usr/share/aclocal
    - /usr/share/pkgconfig
    - /usr/share/gtk-doc/data
setup      : |
    %patch -p1 < $pkgfiles/docbook.patch
    autoreconf -vfi
    %configure
build      : |
    %make
install    : |
    %make_install
