name       : gtk-doc
version    : '1.28'
release    : 6
source     :
    - https://download.gnome.org/sources/gtk-doc/1.28/gtk-doc-1.28.tar.xz : 911e29e302252c96128965ee1f4067d5431a88e00ad1023a8bc1d6b922af5715
homepage   : https://www.gtk.org/gtk-doc/
license    : GPL-2.0
component  : desktop.gnome.doc
summary    : GTK API Documentation generator
description: |
    GTK-Doc is a project which was started to generate API documentation from comments added to C code. It is typically used to document the public API of GTK+ and GNOME libraries, but it can also be used to document application code.
builddeps  :
    - docbook-xml
    - highlight
rundeps    :
    - docbook-xml
    - highlight
    - python-six
patterns   :
    - /usr/share/aclocal
    - /usr/share/pkgconfig
    - /usr/share/gtk-doc/data
setup      : |
    %patch -p1 < $pkgfiles/docbook.patch
    %reconfigure
build      : |
    %make
install    : |
    %make_install
